services:
  - type: web
    name: consolata
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn consolata.wsgi
    envVars:
      - key: SECRET_KEY
        value: django-insecure-vvccg6^@(asd7g(kwtw298^7@f0p09n^)o3eji)%!#&$c8te#a
      - key: DJANGO_SETTINGS_MODULE
        value: consolata.settings

