# Generated by Django 5.0.14 on 2025-05-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblTeachersPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('normal_mark1', models.CharField(max_length=5)),
                ('normal_mark2', models.CharField(max_length=5)),
                ('special_mark', models.CharField(max_length=5)),
                ('number_normal', models.IntegerField()),
                ('special_number', models.IntegerField()),
                ('onsite_mark', models.CharField(max_length=5)),
                ('onsite_number', models.IntegerField()),
                ('normal_class_hours', models.IntegerField()),
                ('normal_class_total', models.IntegerField()),
                ('afternoon_activity_rate', models.IntegerField()),
                ('activities_hours', models.IntegerField()),
                ('activities_total', models.IntegerField()),
                ('quality_work_rate', models.IntegerField()),
                ('tod_hours', models.IntegerField()),
                ('tod_total', models.IntegerField()),
                ('special_class_rate', models.IntegerField()),
                ('tutored_hours', models.IntegerField()),
                ('tutored_total', models.IntegerField()),
                ('eca_rate', models.IntegerField()),
                ('eca_hours', models.IntegerField()),
                ('eca_total', models.IntegerField()),
                ('meeting_rate', models.IntegerField()),
                ('meeting_number', models.IntegerField()),
                ('meeting_total', models.IntegerField()),
                ('placement_rate', models.IntegerField()),
                ('test_number', models.IntegerField()),
                ('test_total', models.IntegerField()),
                ('internet_total', models.IntegerField()),
                ('normal_class2_rate', models.IntegerField()),
                ('normal2_hours', models.IntegerField()),
                ('normal2_total', models.IntegerField()),
                ('onsite_rate', models.IntegerField()),
                ('onsite_hours', models.IntegerField()),
                ('onsite_total', models.IntegerField()),
                ('salaries', models.IntegerField()),
                ('summation1', models.IntegerField()),
                ('advance', models.IntegerField()),
                ('advance_total', models.IntegerField()),
                ('charity', models.IntegerField()),
                ('charity_total', models.IntegerField()),
                ('others', models.IntegerField()),
                ('others_total', models.IntegerField()),
                ('summation2', models.IntegerField()),
                ('gross_total', models.IntegerField()),
                ('date_submitted', models.DateTimeField()),
                ('payment_status', models.CharField(max_length=10)),
                ('approval_status', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'tbl_teachers_pay',
                'managed': False,
            },
        ),
    ]
