# Generated by Django 5.0.14 on 2025-06-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0003_tblrecordslip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=200, null=True)),
                ('class_no', models.IntegerField()),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
