# Generated by Django 5.0.14 on 2025-06-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0004_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='courses',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
