# Generated by Django 5.0.14 on 2025-06-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0005_timetable_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='time',
            new_name='from_time',
        ),
        migrations.AddField(
            model_name='timetable',
            name='to_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
