# Generated by Django 5.0.14 on 2025-06-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0006_rename_time_timetable_from_time_timetable_to_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
