# Generated by Django 5.0.14 on 2025-06-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0008_studentsresults'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentsResults',
        ),
    ]
