# Generated by Django 5.0.14 on 2025-06-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblstudentsadmissions',
            name='sir_name',
        ),
    ]
