# Generated by Django 5.0.14 on 2025-05-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblStudentsAdmission',
        ),
    ]
