# Generated by Django 5.0.14 on 2025-05-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_delete_tblstudentsadmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblStudentsAdmission',
            fields=[
                ('studentid', models.AutoField(db_column='studentID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='consolata_admin/student')),
                ('nationality', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('id_passport', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('admission_year', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('billing_self', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('responsible', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('language_spoken', models.CharField(max_length=100)),
                ('language_to_learn', models.CharField(max_length=100)),
                ('course_type', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('other_courses', models.CharField(max_length=100)),
                ('sponsor', models.CharField(blank=True, max_length=254, null=True)),
                ('registration_number', models.IntegerField()),
                ('modality', models.CharField(max_length=100)),
                ('mail_status', models.CharField(max_length=20)),
                ('type_of_sponsorship', models.CharField(blank=True, choices=[('Self', 'Self'), ('Congregation', 'Congregation')], max_length=254, null=True)),
            ],
            options={
                'db_table': 'tbl_students_admission',
                'managed': False,
            },
        ),
    ]
