# Generated by Django 5.0.14 on 2025-06-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_tblstudentsadmissions_sir_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblStudentsAdmissions',
        ),
    ]
