# Generated by Django 5.0.14 on 2025-06-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0003_delete_tblstudentsadmissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblStudentsAdmissions',
            fields=[
                ('studentid', models.AutoField(db_column='studentID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sir_name', models.CharField(blank=True, max_length=100, null=True)),
                ('other_names', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('diocese', models.CharField(blank=True, max_length=100, null=True)),
                ('congregation', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_adress', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin_address', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin_email', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='consolata_admin/student')),
                ('nationality', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('id_passport', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('admission_year', models.CharField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2025, max_length=20)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('billing_self', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('responsible', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('language_spoken', models.CharField(max_length=100)),
                ('language_to_learn', models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Spanish', 'Spanish'), ('Arabic', 'Arabic'), ('Chinese', 'Chinese'), ('Russian', 'Russian'), ('German', 'German'), ('Portuguese', 'Portuguese'), ('Hindi', 'Hindi'), ('Japanese', 'Japanese'), ('Italian', 'Italian'), ('Kiswahili', 'Kiswahili'), ('Kenyan Sign Language', 'Kenyan Sign Language'), ('Korean', 'Korean'), ('Turkish', 'Turkish'), ('Bengali', 'Bengali'), ('Persian', 'Persian'), ('Punjabi', 'Punjabi'), ('Urdu', 'Urdu'), ('Indonesian', 'Indonesian'), ('Malay', 'Malay'), ('Tamil', 'Tamil'), ('Thai', 'Thai'), ('Dutch', 'Dutch'), ('Polish', 'Polish'), ('Romanian', 'Romanian'), ('Vietnamese', 'Vietnamese'), ('Ukrainian', 'Ukrainian'), ('Greek', 'Greek'), ('Hebrew', 'Hebrew'), ('Amharic', 'Amharic')], max_length=100)),
                ('course_type', models.CharField(choices=[('Normal', 'Normal'), ('Special', 'Special'), ('Evening & Weekend', 'Evening & Weekend'), ('Onsite', 'Onsite')], max_length=100)),
                ('duration', models.CharField(choices=[('1 Months', '1 Months'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('4 Months', '4 Months')], max_length=20)),
                ('start_date', models.DateField()),
                ('other_courses', models.CharField(choices=[('None', 'None'), ('Computer Packages', 'Computer Packages'), ('ICT Basic Training', 'ICT Basic Training'), ('English', 'English'), ('TOEFL', 'TOEFL'), ('IELTS', 'IELTS'), ('PITMAN', 'PITMAN'), ('ITALIAN', 'ITALIAN'), ('CIL', 'CIL'), ('FRENCH', 'FRENCH'), ('DELF', 'DELF'), ('DALF', 'DALF')], max_length=100)),
                ('sponsor', models.CharField(blank=True, max_length=254, null=True)),
                ('registration_number', models.IntegerField()),
                ('modality', models.CharField(choices=[('On Campus Study', 'On Campus Study'), ('Online Study', 'Online Study'), ('Both', 'Both')], max_length=100)),
                ('mail_status', models.CharField(max_length=20)),
                ('type_of_sponsorship', models.CharField(blank=True, choices=[('Self', 'Self'), ('Congregation', 'Congregation')], max_length=254, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Priest', 'Priest'), ('Deacon', 'Deacon'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Seminarian', 'Seminarian')], max_length=254, null=True)),
                ('registration_status', models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Auditing', 'Auditing'), ('Weekend', 'Weekend'), ('Part-Time', 'Part-Time'), ('Evening Study', 'Evening Study'), ('Distance Learning', 'Distance Learning')], max_length=254, null=True)),
                ('school', models.CharField(blank=True, choices=[('School Of Philosophy', 'School Of Philosophy'), ('School Of Thiology', 'School Of Thiology'), ('School Of Counselling Psychology', 'School Of Counselling Psychology')], max_length=254, null=True)),
                ('school_of_philosophy', models.CharField(blank=True, choices=[('Baccalaureate In Philosophy', 'Baccalaureate In Philosophy'), ('Bachelor Of Philosophy', 'Bachelor Of Philosophy'), ('Diploma In Philosophy', 'Diploma In Philosophy'), ('Certificate In Philosophy', 'Certificate In Philosophy'), ('No Award', 'No Award')], max_length=254, null=True)),
                ('school_of_theology', models.CharField(blank=True, choices=[('Baccalaureate In Theology (STB)', 'Baccalaureate In Theology (STB)'), ('Bachelor Of Theology (BATh)', 'Bachelor Of Theology (BATh)'), ('Diploma In Theology', 'Diploma In Theology'), ('Diploma In Religious Studies', 'Diploma In Religious Studies'), ('Certificate In Theology', 'Certificate In Theology'), ('Certificate In Religious Studies', 'Certificate In Religious Studies'), ('No Award', 'No Award')], max_length=254, null=True)),
                ('school_of_counselling', models.CharField(blank=True, choices=[('Bachelor In Counselling Psychology', 'Bachelor In Counselling Psychology'), ('Diploma In Counselling Psychology', 'Diploma In Counselling Psychology'), ('Certificate In Counselling Psychology', 'Certificate In Counselling Psychology'), ('No Award', 'No Award')], max_length=254, null=True)),
                ('anticipated_program_duration', models.CharField(blank=True, choices=[('1 Years', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years')], max_length=254, null=True)),
                ('ever_studied_at_ciu', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=254, null=True)),
                ('previous_stud_id', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_ciu_school', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_from_year', models.CharField(blank=True, max_length=100, null=True)),
                ('prev_to_year', models.CharField(blank=True, max_length=100, null=True)),
                ('colleges_attended', models.CharField(blank=True, max_length=100, null=True)),
                ('high_school_attended', models.CharField(blank=True, max_length=100, null=True)),
                ('recommending_authority', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('recomendation_type', models.CharField(blank=True, choices=[('Congregation', 'Congregation'), ('Diocese', 'Diocese'), ('Organisation', 'Organisation')], max_length=254, null=True)),
                ('disability', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=254, null=True)),
            ],
            options={
                'db_table': 'tbl_students_admissions',
                'managed': True,
            },
        ),
    ]
