# Generated by Django 5.0.14 on 2025-05-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblStudentsAdmission',
        ),
    ]
