# Generated by Django 5.0.14 on 2025-06-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='confirm_information',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='copies_of_diplomas',
            field=models.FileField(blank=True, null=True, upload_to='online-application/'),
        ),
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='coppy_of_all_degrees',
            field=models.FileField(blank=True, null=True, upload_to='online-application/'),
        ),
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='copy_of_id',
            field=models.FileField(blank=True, null=True, upload_to='online-application/'),
        ),
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='disability_nature',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='how_fee_will_be_paid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='how_you_knew_consolata',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='non_refundable_fee',
            field=models.FileField(blank=True, null=True, upload_to='online-application/'),
        ),
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='passport_photo',
            field=models.FileField(blank=True, null=True, upload_to='online-application/'),
        ),
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='recomendation_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='recomendation_email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='recommending_congregation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='sponsor_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='sponsor_email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='sponsor_phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='sponsor_recomendation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='sponsorship_community',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
