# Generated by Django 5.0.14 on 2025-05-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0004_delete_tblstudentsadmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblStudentsAdmission',
            fields=[
                ('studentid', models.AutoField(db_column='studentID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='consolata_admin/student')),
                ('nationality', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('id_passport', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('admission_year', models.CharField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2025, max_length=20)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('billing_self', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('responsible', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('language_spoken', models.CharField(max_length=100)),
                ('language_to_learn', models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Spanish', 'Spanish'), ('Arabic', 'Arabic'), ('Chinese', 'Chinese'), ('Russian', 'Russian'), ('German', 'German'), ('Portuguese', 'Portuguese'), ('Hindi', 'Hindi'), ('Japanese', 'Japanese'), ('Italian', 'Italian'), ('Kiswahili', 'Kiswahili'), ('Kenyan Sign Language', 'Kenyan Sign Language'), ('Korean', 'Korean'), ('Turkish', 'Turkish'), ('Bengali', 'Bengali'), ('Persian', 'Persian'), ('Punjabi', 'Punjabi'), ('Urdu', 'Urdu'), ('Indonesian', 'Indonesian'), ('Malay', 'Malay'), ('Tamil', 'Tamil'), ('Thai', 'Thai'), ('Dutch', 'Dutch'), ('Polish', 'Polish'), ('Romanian', 'Romanian'), ('Vietnamese', 'Vietnamese'), ('Ukrainian', 'Ukrainian'), ('Greek', 'Greek'), ('Hebrew', 'Hebrew'), ('Amharic', 'Amharic')], max_length=100)),
                ('course_type', models.CharField(choices=[('Normal', 'Normal'), ('Special', 'Special'), ('Evening & Weekend', 'Evening & Weekend'), ('Onsite', 'Onsite')], max_length=100)),
                ('duration', models.CharField(choices=[('1 Months', '1 Months'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('4 Months', '4 Months')], max_length=20)),
                ('start_date', models.DateField()),
                ('other_courses', models.CharField(choices=[('None', 'None'), ('Computer Packages', 'Computer Packages'), ('ICT Basic Training', 'ICT Basic Training'), ('English', 'English'), ('TOEFL', 'TOEFL'), ('IELTS', 'IELTS'), ('PITMAN', 'PITMAN'), ('ITALIAN', 'ITALIAN'), ('CIL', 'CIL'), ('FRENCH', 'FRENCH'), ('DELF', 'DELF'), ('DALF', 'DALF')], max_length=100)),
                ('sponsor', models.CharField(blank=True, max_length=254, null=True)),
                ('registration_number', models.IntegerField()),
                ('modality', models.CharField(choices=[('On Campus Study', 'On Campus Study'), ('Online Study', 'Online Study'), ('Both', 'Both')], max_length=100)),
                ('mail_status', models.CharField(max_length=20)),
                ('type_of_sponsorship', models.CharField(blank=True, choices=[('Self', 'Self'), ('Congregation', 'Congregation')], max_length=254, null=True)),
            ],
            options={
                'db_table': 'tbl_students_admission',
                'managed': False,
            },
        ),
    ]
