# Generated by Django 5.0.14 on 2025-06-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_tblstudentsadmissions_confirm_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='coppy_of_qualifications',
            field=models.FileField(blank=True, null=True, upload_to='online-application/'),
        ),
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='recomendation_phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tblstudentsadmissions',
            name='school',
            field=models.CharField(blank=True, choices=[('School Of Philosophy', 'School Of Philosophy'), ('School Of Theology', 'School Of Theology'), ('School Of Counselling Psychology', 'School Of Counselling Psychology')], max_length=254, null=True),
        ),
    ]
