# Generated by Django 5.0.14 on 2025-06-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_tblstudentsadmissions_coppy_of_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentsadmissions',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
