# Generated by Django 5.0.14 on 2025-06-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_tblstudentsadmissions_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='coppy_of_transcripts',
            field=models.FileField(blank=True, null=True, upload_to='online-application/'),
        ),
    ]
