# Generated by Django 5.0.14 on 2025-06-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_tblstudentsadmissions_coppy_of_transcripts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentsadmissions',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='online-application/'),
        ),
    ]
