# Generated by Django 5.0.14 on 2025-06-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_tblstudentsadmissions_passport_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassSignIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congregation', models.CharField(blank=True, max_length=250, null=True)),
                ('S_no', models.IntegerField(blank=True, null=True)),
                ('Reg_no', models.IntegerField(blank=True, null=True)),
                ('student_name', models.CharField(blank=True, max_length=250, null=True)),
                ('sign', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
