# Generated by Django 5.0.14 on 2025-06-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentclasssignin'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclasssignin',
            name='cmm',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='studentclasssignin',
            name='cssr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='studentclasssignin',
            name='fdp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='studentclasssignin',
            name='mcf',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='studentclasssignin',
            name='o_carm',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='studentclasssignin',
            name='omi',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='studentclasssignin',
            name='osa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='studentclasssignin',
            name='ssc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='studentclasssignin',
            name='svi',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
