# Generated by Django 5.0.14 on 2025-06-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_studentclasssignin_cmm_studentclasssignin_cssr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclasssignin',
            old_name='Reg_no',
            new_name='reg_no',
        ),
        migrations.RenameField(
            model_name='studentclasssignin',
            old_name='S_no',
            new_name='s_no',
        ),
    ]
